# NOTE
# If the directory path contains spaces, please enclose it in double quotes.
# Ex. "/WorkDIR/some SDK/include"

# Select Screen Type
# DESKTOP_SCREEN_MODE: Used for displaying on a regular desktop display. In this mode, the application is shown on a standard display device.(Default)
# OPENXR_SCREEN_MODE: Used for displaying with the OpenXR SDK. This mode utilizes OpenXR to render the application on supported devices.
DESKTOP_SCREEN_MODE = 1
OPENXR_SCREEN_MODE = 0

# FBXSDK : If you wish to visualize the .fbx format
PBVR_SUPPORT_FBX=0
FBXSDK_INC_DIR =
FBXSDK_LIB_DIR =

PBVR_SUPPORT_3DS=0
# ASSIMP : If you wish to visualize the .3ds format
ASSIMP_INC_DIR =
ASSIMP_LIB_DIR =
