if(${CMAKE_BUILD_TYPE} STREQUAL "RELEASE")
  set(RELEASE ON)
  set(DEBUG OFF)
else()
  set(RELEASE OFF)
  set(DEBUG ON)
endif()
set(CMAKE_PREFIX_PATH_ORIG CMAKE_PREFIX_PATH)
list(APPEND CMAKE_PREFIX_PATH ${CMAKE_CURRENT_SOURCE_DIR}/Library/KVS/Source)
set(KVS_TOOL OFF)

add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/Library/KVS)

set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH_ORIG})
