# NOTE
# If the directory path contains spaces, please enclose it in double quotes.
# Ex. "/WorkDIR/some SDK/include"

# equired library
# KVS : Path to KVS installation
KVS_DIR =

# optional library
# FBXSDK : If you wish to visualize the .fbx format
PBVR_SUPPORT_FBX=1
FBXSDK_INC_DIR =
FBXSDK_LIB_DIR =

PBVR_SUPPORT_3DS=1
# ASSIMP : If you wish to visualize the .3ds format
ASSIMP_INC_DIR =
ASSIMP_LIB_DIR =
