#NOTE
# If the directory path contains spaces, please enclose it in double quotes.
# Ex. "/WorkDIR/some SDK/include"

#equired library
# KVS : Path to KVS installation
KVS_DIR = /Users/t0603/Work/PBVR/lib/KVS_FOR_QTPBVR_release3.0.0/install

#optional library
# FBXSDK : If you wish to visualize the .fbx format
PBVR_SUPPORT_FBX=1
FBXSDK_INC_DIR = "/Applications/Autodesk/FBX SDK/2020.3.4/include"
FBXSDK_LIB_DIR = "/Applications/Autodesk/FBX SDK/2020.3.4/lib/clang/release"

PBVR_SUPPORT_3DS=1
# ASSIMP : If you wish to visualize the .3ds format
ASSIMP_INC_DIR = /Users/t0603/Work/PBVR/lib/assimp-5.0.0/include
ASSIMP_LIB_DIR = /Users/t0603/Work/PBVR/lib/assimp-5.0.0/lib
