# NOTE
# If the directory path contains spaces, please enclose it in double quotes.
# Ex. "/WorkDIR/some SDK/include"

# optional library
# FBXSDK : If you wish to visualize the .fbx format
PBVR_SUPPORT_FBX=0
FBXSDK_INC_DIR =
FBXSDK_LIB_DIR =

PBVR_SUPPORT_3DS=0
# ASSIMP : If you wish to visualize the .3ds format
ASSIMP_INC_DIR =
ASSIMP_LIB_DIR =
