# Toggle individual Qt tests here.
# 1 = enabled, 0 = disabled

TEST_ENABLE_MENUBAR = 0
TEST_ENABLE_SCREEN = 0
TEST_ENABLE_PLAYBACKCONTROLTOOLBAR = 0
TEST_ENABLE_TIMESTEPCONTROLTOOLBAR = 0
TEST_ENABLE_COLORMAPSELECTORTOOLBAR = 0
TEST_ENABLE_TOTALPARTICLESTOOLBAR = 0
TEST_ENABLE_PREFERENCE = 0
TEST_ENABLE_COMMUNICATION = 0
TEST_ENABLE_COMMUNICATION_USER_INFO = 0
TEST_ENABLE_COMMUNICATION_SETTING = 0
TEST_ENABLE_COMMUNICATION_SHARE_VIEW = 0
TEST_ENABLE_ANIMATIONCONTROL = 0
TEST_ENABLE_GLYPHEDITOR = 0
TEST_ENABLE_OBJECTEDITOR = 0
TEST_ENABLE_PLOTOVERLINEEDITOR = 0
TEST_ENABLE_POINTSIZECONTROL = 0
TEST_ENABLE_REPETITIONLEVELCONTROL = 0
TEST_ENABLE_SHADINGCONTROL = 0
TEST_ENABLE_SERVER = 1
TEST_ENABLE_INSITU_MODE = 0
TEST_ENABLE_ENSEMBLE_TRANSFER_FUNCTION = 0
TEST_ENABLE_TRANSFERFUNCTIONEDITOR_IMPORTEXPORT = 0
TEST_ENABLE_TRANSFERFUNCTIONEDITOR_CHANGE_TRANSFER_FUNCTION_NUMBER = 0
TEST_ENABLE_TRANSFERFUNCTIONEDITOR_COLOR_FUNCTION_SYNTHESIZER = 0
TEST_ENABLE_TRANSFERFUNCTIONEDITOR_COLOR_FUNCTION_VARIABLE = 0
TEST_ENABLE_TRANSFERFUNCTIONEDITOR_COLOR_MIN_MAX = 0
TEST_ENABLE_TRANSFERFUNCTIONEDITOR_COLOR_MAP_EDIT = 0
TEST_ENABLE_TRANSFERFUNCTIONEDITOR_OPACITY_FUNCTION_SYNTHESIZER = 0
TEST_ENABLE_TRANSFERFUNCTIONEDITOR_OPACITY_FUNCTION_VARIABLE = 0
TEST_ENABLE_TRANSFERFUNCTIONEDITOR_OPACITY_MIN_MAX = 0
TEST_ENABLE_TRANSFERFUNCTIONEDITOR_OPACITY_MAP_EDIT = 0
TEST_ENABLE_VOLUMETRANSFORM = 0
