#ifndef _TIMER_SIMPLE_H_INCLUDE
#define _TIMER_SIMPLE_H_INCLUDE

#define VIS_MODULE_TIMER_COUNT_NUM 9

#ifdef _TIMER_
#define VIS_MODULE_TIMER_INIT()
#define VIS_MODULE_TIMER_FIN()
#define VIS_MODULE_TIMER_STA(id)
#define VIS_MODULE_TIMER_END(id)
#define VIS_MODULE_TIMER_BAR(id)
#else
#define VIS_MODULE_TIMER_INIT()
#define VIS_MODULE_TIMER_FIN()
#define VIS_MODULE_TIMER_STA(id)
#define VIS_MODULE_TIMER_END(id)
#define VIS_MODULE_TIMER_BAR(id)
#endif

#endif
