#ifndef TASK_SIGNAL_H
#define TASK_SIGNAL_H

enum class TaskSignal : int
{
    EXIT = -1,
    WAITING = 0,
    INITIAL_STEP = 1,
    GENERATE_PARTICLE,
    GENERATE_GLYPH,
    GENERATE_PLOT_OVER_LINE,
    UPDATE_PARTICLE_PROPERTY,
    UPDATE_GLYPH_PROPERTY,
    UPDATE_PLOT_OVER_LINE_PROPERTY,
    UPDATE_PLOT_OVER_TIME_PROPERTY,
};

#endif // TASK_SIGNAL_h
