site_name: kvsml-converterマニュアル
copyright: © Japan Atomic Energy Agency
nav:
  - index.md
  - install.md
  - tutorial/gettingstarted.md
  - tutorial/basics.md
  - tutorial/eachcelltype.md
  - tutorial/eachpiece.md
  - tutorial/eachtimestep.md
  - tutorial/eachblock.md
  - examplelist.md
use_directory_urls: false
markdown_extensions:
  - toc:
      permalink: True
plugins:
  - pandoc:
      combined: true
      enabled_if_env: ENABLE_PANDOC_EXPORT