#  DON'T EDIT THIS FILE.
#  THIS IS GENERATED BY "Configuration/configure_BuildRule.py".


OBJECTS = \
$(OUTDIR)\.\Viewer\Application.obj \
$(OUTDIR)\.\Viewer\Camera.obj \
$(OUTDIR)\.\Viewer\Configuration.obj \
$(OUTDIR)\.\Viewer\MainLoop.obj \
$(OUTDIR)\.\Viewer\Master.obj \
$(OUTDIR)\.\Viewer\Screen.obj \
$(OUTDIR)\.\Viewer\Trackpad.obj \



{.\Viewer\}.cpp{$(OUTDIR)\.\Viewer\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Viewer $(MKDIR) $(OUTDIR)\.\Viewer
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Viewer\ @<<
$<
<<


install::
	IF NOT EXIST $(INSTALL_DIR)\include\SupportOpenCABIN\. $(MKDIR) $(INSTALL_DIR)\include\SupportOpenCABIN\.
	$(INSTALL) .\*.h $(INSTALL_DIR)\include\SupportOpenCABIN\.
	IF NOT EXIST $(INSTALL_DIR)\include\SupportOpenCABIN\.\Viewer $(MKDIR) $(INSTALL_DIR)\include\SupportOpenCABIN\.\Viewer
	$(INSTALL) .\Viewer\*.h $(INSTALL_DIR)\include\SupportOpenCABIN\.\Viewer
