#PBVR_MACHINE=Makefile_machine_gcc_mpi_omp
#PBVR_MACHINE=Makefile_machine_s86_mpi_omp
PBVR_MACHINE=Makefile_machine_s86_omp
#PBVR_MACHINE=Makefile_machine_mac_gcc_omp
PBVR_MAKE_FILTER=1
PBVR_MAKE_SERVER=1
PBVR_MAKE_KVSML_COMVERTER=1
PBVR_SUPPORT_VTK=0
ISPBVR_SUPPORT_VTK=1
