#  DON'T EDIT THIS FILE.
#  THIS IS GENERATED BY "Configuration/configure_BuildRule.py".


OBJECTS := \
$(OUTDIR)/./Context.o \
$(OUTDIR)/./Device.o \



$(OUTDIR)/./%.o: ./%.cpp ./%.h
	$(MKDIR) $(OUTDIR)/.
	$(CPP) -c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) -o $@ $<


install::
	$(MKDIR) $(INSTALL_DIR)/include/SupportCUDA/.
	$(INSTALL) ./*.h $(INSTALL_DIR)/include/SupportCUDA/.
