rm -f history_0*
rm -f default_0*
rm -f timer.out.*
rm -f particle_out/*
rm -f state.txt
cp default_old.tf default.tf
cp default_old.json default.json
cp parameter_old.gly parameter.gly
cp parameter_old.pol parameter.pol
cp parameter_old.pot parameter.pot
